// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/ambassador" | "/ambassador/dashboard" | "/app" | "/app/edit" | "/apps" | "/apps/[slug]" | "/billing/cancel" | "/billing/history" | "/billing/success" | "/checkout" | "/create" | "/createx" | "/debug-fix" | "/dev/auth-verify-logs" | "/dev/env" | "/dev/env/firebase-check" | "/dev/firebase-check" | "/dev/firebase-web-ping" | "/dev/play-debug" | "/dev/sse/[buildId]" | "/dev/whoami" | "/diag/env" | "/docs" | "/doctor" | "/donate/thank-you" | "/faq" | "/golden-book" | "/inactive" | "/jednostavne-upute" | "/legacy-handle" | "/legal/privacy" | "/legal/refunds" | "/legal/terms" | "/login" | "/moderation" | "/my" | "/my-creators" | "/oglasi" | "/oglasi/novi" | "/paywall" | "/play/[appId]" | "/politika-privatnosti" | "/pravila-koristenja" | "/prijava-sadrzaja" | "/privacy" | "/pro" | "/pro-apps" | "/pro/checkout" | "/profile" | "/profile/edit" | "/redeem" | "/register" | "/search" | "/settings" | "/setup" | "/u" | "/u/[username]" | "/u/admin" | "/u/finances"
type AppRouteHandlerRoutes = "/api/jwt" | "/api/listing" | "/docs/raw" | "/play"
type PageRoutes = "/_document"
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = "/[segment]/favicon.ico" | "/api/[[...path]]" | "/api/avatar/[[...path]]" | "/api/health" | "/api/listing/[[...path]]" | "/api/listings" | "/api/oglasi" | "/api/review/[[...path]]" | "/app/[[...path]]" | "/billing/[[...path]]" | "/build/[[...path]]" | "/builds/[[...path]]" | "/play-wrapper.js" | "/play.css" | "/public/builds/[[...path]]" | "/review/builds/[[...path]]" | "/shims/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/_document": {}
  "/[segment]/favicon.ico": { "segment": string; }
  "/about": {}
  "/admin": {}
  "/admin/ambassador": {}
  "/ambassador/dashboard": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/api/avatar/[[...path]]": { "path"?: string[]; }
  "/api/health": {}
  "/api/jwt": {}
  "/api/listing": {}
  "/api/listing/[[...path]]": { "path"?: string[]; }
  "/api/listings": {}
  "/api/oglasi": {}
  "/api/review/[[...path]]": { "path"?: string[]; }
  "/app": {}
  "/app/[[...path]]": { "path"?: string[]; }
  "/app/edit": {}
  "/apps": {}
  "/apps/[slug]": { "slug": string; }
  "/billing/[[...path]]": { "path"?: string[]; }
  "/billing/cancel": {}
  "/billing/history": {}
  "/billing/success": {}
  "/build/[[...path]]": { "path"?: string[]; }
  "/builds/[[...path]]": { "path"?: string[]; }
  "/checkout": {}
  "/create": {}
  "/createx": {}
  "/debug-fix": {}
  "/dev/auth-verify-logs": {}
  "/dev/env": {}
  "/dev/env/firebase-check": {}
  "/dev/firebase-check": {}
  "/dev/firebase-web-ping": {}
  "/dev/play-debug": {}
  "/dev/sse/[buildId]": { "buildId": string; }
  "/dev/whoami": {}
  "/diag/env": {}
  "/docs": {}
  "/docs/raw": {}
  "/doctor": {}
  "/donate/thank-you": {}
  "/faq": {}
  "/golden-book": {}
  "/inactive": {}
  "/jednostavne-upute": {}
  "/legacy-handle": {}
  "/legal/privacy": {}
  "/legal/refunds": {}
  "/legal/terms": {}
  "/login": {}
  "/moderation": {}
  "/my": {}
  "/my-creators": {}
  "/oglasi": {}
  "/oglasi/novi": {}
  "/paywall": {}
  "/play": {}
  "/play-wrapper.js": {}
  "/play.css": {}
  "/play/[appId]": { "appId": string; }
  "/politika-privatnosti": {}
  "/pravila-koristenja": {}
  "/prijava-sadrzaja": {}
  "/privacy": {}
  "/pro": {}
  "/pro-apps": {}
  "/pro/checkout": {}
  "/profile": {}
  "/profile/edit": {}
  "/public/builds/[[...path]]": { "path"?: string[]; }
  "/redeem": {}
  "/register": {}
  "/review/builds/[[...path]]": { "path"?: string[]; }
  "/search": {}
  "/settings": {}
  "/setup": {}
  "/shims/[[...path]]": { "path"?: string[]; }
  "/u": {}
  "/u/[username]": { "username": string; }
  "/u/admin": {}
  "/u/finances": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
