// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type PagesPageConfig = {
  default: React.ComponentType<any> | ((props: any) => React.ReactNode | Promise<React.ReactNode> | never | void)
  getStaticProps?: (context: any) => Promise<any> | any
  getStaticPaths?: (context: any) => Promise<any> | any
  getServerSideProps?: (context: any) => Promise<any> | any
  getInitialProps?: (context: any) => Promise<any> | any
  /**
   * Segment configuration for legacy Pages Router pages.
   * Validated at build-time by parsePagesSegmentConfig.
   */
  config?: {
    amp?: boolean | 'hybrid' | string // necessary for JS
    maxDuration?: number
    runtime?: 'edge' | 'experimental-edge' | 'nodejs' | string // necessary unless config is exported as const
    regions?: string[]
  }
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(node)/dev/firebase-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/firebase-check">> = Specific
  const handler = {} as typeof import("../../app/(node)/dev/firebase-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(node)/dev/firebase-web-ping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/firebase-web-ping">> = Specific
  const handler = {} as typeof import("../../app/(node)/dev/firebase-web-ping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/ambassador/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ambassador">> = Specific
  const handler = {} as typeof import("../../app/admin/ambassador/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ambassador/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ambassador/dashboard">> = Specific
  const handler = {} as typeof import("../../app/ambassador/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/edit">> = Specific
  const handler = {} as typeof import("../../app/app/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/apps/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apps/[slug]">> = Specific
  const handler = {} as typeof import("../../app/apps/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/apps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apps">> = Specific
  const handler = {} as typeof import("../../app/apps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/billing/cancel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing/cancel">> = Specific
  const handler = {} as typeof import("../../app/billing/cancel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/billing/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing/history">> = Specific
  const handler = {} as typeof import("../../app/billing/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/billing/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing/success">> = Specific
  const handler = {} as typeof import("../../app/billing/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create">> = Specific
  const handler = {} as typeof import("../../app/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/createx/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/createx">> = Specific
  const handler = {} as typeof import("../../app/createx/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/debug-fix/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug-fix">> = Specific
  const handler = {} as typeof import("../../app/debug-fix/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev/auth-verify-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/auth-verify-logs">> = Specific
  const handler = {} as typeof import("../../app/dev/auth-verify-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev/env/firebase-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/env/firebase-check">> = Specific
  const handler = {} as typeof import("../../app/dev/env/firebase-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev/env/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/env">> = Specific
  const handler = {} as typeof import("../../app/dev/env/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev/play-debug/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/play-debug">> = Specific
  const handler = {} as typeof import("../../app/dev/play-debug/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev/sse/[buildId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/sse/[buildId]">> = Specific
  const handler = {} as typeof import("../../app/dev/sse/[buildId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev/whoami/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/whoami">> = Specific
  const handler = {} as typeof import("../../app/dev/whoami/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/diag/env/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/diag/env">> = Specific
  const handler = {} as typeof import("../../app/diag/env/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor">> = Specific
  const handler = {} as typeof import("../../app/doctor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/donate/thank-you/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/donate/thank-you">> = Specific
  const handler = {} as typeof import("../../app/donate/thank-you/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/golden-book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/golden-book">> = Specific
  const handler = {} as typeof import("../../app/golden-book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/inactive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inactive">> = Specific
  const handler = {} as typeof import("../../app/inactive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jednostavne-upute/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jednostavne-upute">> = Specific
  const handler = {} as typeof import("../../app/jednostavne-upute/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/legacy-handle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legacy-handle">> = Specific
  const handler = {} as typeof import("../../app/legacy-handle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/legal/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/privacy">> = Specific
  const handler = {} as typeof import("../../app/legal/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/legal/refunds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/refunds">> = Specific
  const handler = {} as typeof import("../../app/legal/refunds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/legal/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/terms">> = Specific
  const handler = {} as typeof import("../../app/legal/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/moderation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/moderation">> = Specific
  const handler = {} as typeof import("../../app/moderation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/my-creators/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-creators">> = Specific
  const handler = {} as typeof import("../../app/my-creators/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/my/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my">> = Specific
  const handler = {} as typeof import("../../app/my/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/oglasi/novi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/oglasi/novi">> = Specific
  const handler = {} as typeof import("../../app/oglasi/novi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/oglasi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/oglasi">> = Specific
  const handler = {} as typeof import("../../app/oglasi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/paywall/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/paywall">> = Specific
  const handler = {} as typeof import("../../app/paywall/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/play/[appId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/play/[appId]">> = Specific
  const handler = {} as typeof import("../../app/play/[appId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/politika-privatnosti/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/politika-privatnosti">> = Specific
  const handler = {} as typeof import("../../app/politika-privatnosti/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pravila-koristenja/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pravila-koristenja">> = Specific
  const handler = {} as typeof import("../../app/pravila-koristenja/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/prijava-sadrzaja/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prijava-sadrzaja">> = Specific
  const handler = {} as typeof import("../../app/prijava-sadrzaja/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pro-apps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pro-apps">> = Specific
  const handler = {} as typeof import("../../app/pro-apps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pro/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pro/checkout">> = Specific
  const handler = {} as typeof import("../../app/pro/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pro">> = Specific
  const handler = {} as typeof import("../../app/pro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/edit">> = Specific
  const handler = {} as typeof import("../../app/profile/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/redeem/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/redeem">> = Specific
  const handler = {} as typeof import("../../app/redeem/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup">> = Specific
  const handler = {} as typeof import("../../app/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/u/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u/[username]">> = Specific
  const handler = {} as typeof import("../../app/u/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/u/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u/admin">> = Specific
  const handler = {} as typeof import("../../app/u/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/u/finances/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u/finances">> = Specific
  const handler = {} as typeof import("../../app/u/finances/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/u/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u">> = Specific
  const handler = {} as typeof import("../../app/u/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/jwt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jwt">> = Specific
  const handler = {} as typeof import("../../app/api/jwt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/listing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/listing">> = Specific
  const handler = {} as typeof import("../../app/api/listing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/raw/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/docs/raw">> = Specific
  const handler = {} as typeof import("../../app/docs/raw/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/play/(legacy)/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/play">> = Specific
  const handler = {} as typeof import("../../app/play/(legacy)/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../pages/_document.tsx
{
  type __IsExpected<Specific extends PagesPageConfig> = Specific
  const handler = {} as typeof import("../../pages/_document.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}



// Validate ../../app/(node)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(node)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
